### ISSUE TITLE
Great idea!

### ISSUE THREAD

**Issue by denysdovhan** [everylint/everylint#19]
I was thinking about this project a few months ago! I'd even called it the same — _everylint_ 😄

![image](https://user-images.githubusercontent.com/3459374/39678235-6113ab9a-5191-11e8-9782-858fec45ac92.png)

However, I haven't made much. Nevertheless, I have some ideas for this project, so let's do it together! I hope I'll find some time for contributions 🙏

Thanks for making it real!

**Comment by Zmoki** [comment]
@denysdovhan thank you! 

We at @uploadcare have a lot of repos and like linters, but we are too lazy to install and configure them all 😁 So, on Friday I thought it was nice to have one linter and create a project over the weekend.

I will be very happy with your participation.
